import { Recipe } from './types'

export const RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Kimchi Fried Rice',
    description: 'Classic Korean comfort food with tangy kimchi and savory flavors',
    image: '/kimchi-fried-rice-in-a-bowl.jpg',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Cooked rice', amount: '2', unit: 'cups' },
      { name: 'Kimchi', amount: '1', unit: 'cup' },
      { name: 'Onion', amount: '1/2', unit: 'medium' },
      { name: 'Carrot', amount: '1', unit: 'small' },
      { name: 'Green onion', amount: '2', unit: 'stalks' },
      { name: 'Egg', amount: '2', unit: 'large' },
      { name: 'Soy sauce', amount: '2', unit: 'tbsp' },
      { name: 'Sesame oil', amount: '1', unit: 'tbsp' },
      { name: 'Vegetable oil', amount: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Chop kimchi, onion, and carrot into small pieces',
      'Heat vegetable oil in a large pan or wok over medium-high heat',
      'Add onion and carrot, stir-fry for 2-3 minutes',
      'Add kimchi and stir-fry for another 2 minutes',
      'Add rice and break up any clumps, stir-fry for 3-4 minutes',
      'Add soy sauce and sesame oil, mix well',
      'Push rice to the side, crack eggs into the pan and scramble',
      'Mix eggs into rice and garnish with chopped green onions',
    ],
    nutrition: {
      calories: 450,
      protein: 15,
      carbs: 62,
      fat: 16,
      fiber: 3,
    },
    category: 'Main Course',
    cookingTools: ['wok', 'spatula', 'knife'],
    tags: ['quick', 'budget-friendly', 'one-pan'],
  },
  {
    id: '2',
    title: 'Bulgogi Beef Bowl',
    description: 'Tender marinated beef with sweet and savory Korean BBQ flavors',
    image: '/bulgogi-beef-bowl-with-vegetables.jpg',
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: 'medium',
    ingredients: [
      { name: 'Beef sirloin', amount: '500', unit: 'g' },
      { name: 'Soy sauce', amount: '1/4', unit: 'cup' },
      { name: 'Sugar', amount: '2', unit: 'tbsp' },
      { name: 'Garlic', amount: '4', unit: 'cloves' },
      { name: 'Onion', amount: '1', unit: 'large' },
      { name: 'Green onion', amount: '3', unit: 'stalks' },
      { name: 'Sesame oil', amount: '2', unit: 'tbsp' },
      { name: 'Black pepper', amount: '1', unit: 'tsp' },
      { name: 'Sesame seeds', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Slice beef thinly against the grain',
      'Mix soy sauce, sugar, minced garlic, sesame oil, and pepper for marinade',
      'Marinate beef for at least 15 minutes',
      'Slice onion thinly and chop green onions',
      'Heat a large pan over high heat',
      'Cook beef in batches until caramelized, about 3-4 minutes per batch',
      'Add onions in the last batch and cook until softened',
      'Garnish with green onions and sesame seeds',
    ],
    nutrition: {
      calories: 380,
      protein: 32,
      carbs: 18,
      fat: 20,
      fiber: 2,
    },
    category: 'Main Course',
    cookingTools: ['pan', 'knife', 'bowl'],
    tags: ['protein-rich', 'marinated'],
  },
  {
    id: '3',
    title: 'Korean Egg Roll',
    description: 'Fluffy rolled omelette with a hint of sweetness',
    image: '/korean-rolled-egg-omelette-sliced.jpg',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Egg', amount: '4', unit: 'large' },
      { name: 'Green onion', amount: '2', unit: 'stalks' },
      { name: 'Carrot', amount: '1/4', unit: 'cup' },
      { name: 'Salt', amount: '1/4', unit: 'tsp' },
      { name: 'Sugar', amount: '1', unit: 'tsp' },
      { name: 'Vegetable oil', amount: '2', unit: 'tbsp' },
    ],
    instructions: [
      'Beat eggs with salt and sugar',
      'Finely chop green onion and carrot, mix into eggs',
      'Heat a rectangular pan over medium-low heat with oil',
      'Pour a thin layer of egg mixture',
      'When edges set, roll the egg from one end',
      'Push roll to one side, add more egg mixture',
      'Continue rolling and adding layers until egg is finished',
      'Slice into bite-sized pieces',
    ],
    nutrition: {
      calories: 220,
      protein: 14,
      carbs: 4,
      fat: 16,
      fiber: 1,
    },
    category: 'Side Dish',
    cookingTools: ['pan', 'spatula', 'whisk'],
    tags: ['quick', 'breakfast', 'protein-rich'],
  },
  {
    id: '4',
    title: 'Japchae',
    description: 'Stir-fried glass noodles with colorful vegetables',
    image: '/japchae-korean-glass-noodles-with-vegetables.jpg',
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: 'medium',
    ingredients: [
      { name: 'Sweet potato noodles', amount: '200', unit: 'g' },
      { name: 'Spinach', amount: '2', unit: 'cups' },
      { name: 'Carrot', amount: '1', unit: 'large' },
      { name: 'Onion', amount: '1', unit: 'medium' },
      { name: 'Mushrooms', amount: '1', unit: 'cup' },
      { name: 'Bell pepper', amount: '1', unit: 'large' },
      { name: 'Soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'Sugar', amount: '2', unit: 'tbsp' },
      { name: 'Sesame oil', amount: '2', unit: 'tbsp' },
      { name: 'Garlic', amount: '3', unit: 'cloves' },
    ],
    instructions: [
      'Cook noodles according to package directions, drain and cut into shorter lengths',
      'Julienne all vegetables into thin strips',
      'Blanch spinach briefly, squeeze out water',
      'Stir-fry each vegetable separately with a bit of oil and salt',
      'Mix soy sauce, sugar, sesame oil, and minced garlic for sauce',
      'Combine noodles, vegetables, and sauce in a large pan',
      'Toss everything together over medium heat for 2-3 minutes',
      'Garnish with sesame seeds',
    ],
    nutrition: {
      calories: 320,
      protein: 8,
      carbs: 58,
      fat: 8,
      fiber: 5,
    },
    category: 'Main Course',
    cookingTools: ['pot', 'wok', 'knife'],
    tags: ['vegetarian', 'colorful', 'traditional'],
  },
  {
    id: '5',
    title: 'Sundubu Jjigae',
    description: 'Spicy soft tofu stew with seafood and vegetables',
    image: '/sundubu-jjigae-korean-soft-tofu-stew.jpg',
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'Soft tofu', amount: '1', unit: 'package' },
      { name: 'Shrimp', amount: '100', unit: 'g' },
      { name: 'Clams', amount: '100', unit: 'g' },
      { name: 'Onion', amount: '1/2', unit: 'medium' },
      { name: 'Green onion', amount: '2', unit: 'stalks' },
      { name: 'Egg', amount: '2', unit: 'large' },
      { name: 'Gochugaru', amount: '2', unit: 'tbsp' },
      { name: 'Garlic', amount: '3', unit: 'cloves' },
      { name: 'Soy sauce', amount: '1', unit: 'tbsp' },
      { name: 'Sesame oil', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Heat sesame oil in a pot, add minced garlic',
      'Add gochugaru and stir briefly',
      'Add 2 cups water and bring to boil',
      'Add seafood and sliced onion, cook for 5 minutes',
      'Gently add soft tofu in large spoonfuls',
      'Season with soy sauce',
      'Crack eggs on top and let them poach',
      'Garnish with green onions and serve bubbling hot',
    ],
    nutrition: {
      calories: 280,
      protein: 25,
      carbs: 12,
      fat: 15,
      fiber: 3,
    },
    category: 'Soup',
    cookingTools: ['pot', 'ladle', 'knife'],
    tags: ['spicy', 'comforting', 'protein-rich'],
  },
  {
    id: '6',
    title: 'Korean Cucumber Salad',
    description: 'Refreshing and crunchy cucumber side dish',
    image: '/korean-cucumber-salad-with-sesame-seeds.jpg',
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: 'easy',
    ingredients: [
      { name: 'Cucumber', amount: '2', unit: 'large' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
      { name: 'Garlic', amount: '2', unit: 'cloves' },
      { name: 'Green onion', amount: '1', unit: 'stalk' },
      { name: 'Gochugaru', amount: '1', unit: 'tbsp' },
      { name: 'Sesame oil', amount: '1', unit: 'tbsp' },
      { name: 'Rice vinegar', amount: '1', unit: 'tbsp' },
      { name: 'Sugar', amount: '1', unit: 'tsp' },
      { name: 'Sesame seeds', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Slice cucumbers thinly and toss with salt',
      'Let sit for 10 minutes, then squeeze out excess water',
      'Mix minced garlic, gochugaru, sesame oil, vinegar, and sugar',
      'Toss cucumbers with the dressing',
      'Add chopped green onion and sesame seeds',
      'Chill for at least 30 minutes before serving',
    ],
    nutrition: {
      calories: 60,
      protein: 2,
      carbs: 6,
      fat: 4,
      fiber: 2,
    },
    category: 'Side Dish',
    cookingTools: ['knife', 'bowl'],
    tags: ['quick', 'refreshing', 'no-cook', 'vegetarian'],
  },
]

export const COOKING_TOOLS = [
  'wok',
  'pan',
  'pot',
  'knife',
  'bowl',
  'spatula',
  'ladle',
  'whisk',
  'cutting board',
  'measuring cups',
]

export const CATEGORIES = [
  'Main Course',
  'Side Dish',
  'Soup',
  'Appetizer',
  'Dessert',
]
